const root=document.documentElement;
const hero=document.querySelector('.hero-track');
const stage=document.querySelector('.hero-stage');
const header=document.querySelector('.header');
const headerInk=header.cloneNode(true);
headerInk.id='header-ink';headerInk.classList.add('header-ink');headerInk.setAttribute('aria-hidden','true');headerInk.inert=true;
headerInk.innerHTML=headerInk.innerHTML.replaceAll('brand-mask','brand-mask-ink').replaceAll('inverse','inverse-ink').replace('id="language"','');
header.after(headerInk);
const reduce=matchMedia('(prefers-reduced-motion: reduce)');
const overview=new URLSearchParams(location.search).get('view')==='overview';
if(overview)document.body.classList.add('overview');
const clamp=n=>Math.max(0,Math.min(1,n));
function paintHero(){
 const p=overview||reduce.matches?1:clamp(-hero.getBoundingClientRect().top/(hero.offsetHeight-stage.offsetHeight));
 const w=stage.clientWidth,h=stage.clientHeight;
 const start=86, end=Math.hypot(w*.5,h*.51)+10;
 const reveal=clamp(p/.78), smooth=reveal*reveal*(3-2*reveal);
 root.style.setProperty('--radius',`${start+(end-start)*smooth}px`);
 root.style.setProperty('--strip',clamp((p-.22)/.58));
 root.style.setProperty('--bracket',clamp((p-.18)/.15));
 root.style.setProperty('--copy',clamp((p-.68)/.2));
 stage.classList.toggle('complete',p>.82);
 const contact=document.querySelector('#contact').getBoundingClientRect().top<80;
 header.classList.toggle('on-paper',p>=1&&!contact);
 header.classList.toggle('on-blue',contact);
 headerInk.style.clipPath=`circle(${start+(end-start)*smooth}px at ${w*.5}px ${stage.getBoundingClientRect().top+h*.51-header.getBoundingClientRect().top}px)`;
 headerInk.style.visibility=contact?'hidden':'visible';
}
let queued=false;function tick(){if(!queued){queued=true;requestAnimationFrame(()=>{paintHero();queued=false})}}
addEventListener('scroll',tick,{passive:true});addEventListener('resize',tick);reduce.addEventListener('change',tick);paintHero();

let lang='ko', filter='all';
const textOf=value=>typeof value==='string'?value:value[lang];
const categories=[['all','전체','All'],['research','리서치·전략','Research & Strategy'],['experience','경험 설계','Experience Design'],['learning','워크숍·교육','Workshops & Learning']];
const services=[
 {title:'Research<br>& Strategy',ko:'흩어진 신호에서,<br>명확한 방향을.',en:'Find direction<br>in the details.',description:{ko:'사용자와 현장의 맥락을 읽고, 여러 관점의 자료를 제품팀이 판단할 수 있는 기준으로 정리합니다.',en:'Understand people in context. Turn different perspectives into a clear foundation for product decisions.'},scope:'UX Research · Field Study · VoC<br>Problem Framing · UX Strategy',filter:'research'},
 {title:'Experience<br>Design',ko:'화면을 넘어,<br>경험의 흐름으로.',en:'Across screens.<br>Through experiences.',description:{ko:'공간과 화면, 기술과 사람, 사용자와 운영자를 함께 보며 실제로 작동하는 서비스 흐름을 설계합니다.',en:'Connect physical and digital touchpoints, technology and people, customers and operations.'},scope:'Service UX · Product UX · AI Experience<br>Information Architecture · User Flow',filter:'experience'},
 {title:'Workshops<br>& Learning',ko:'함께 이해하고,<br>스스로 실행하도록.',en:'Shared understanding.<br>Confident next steps.',description:{ko:'코디자인 워크숍, UX 교육과 멘토링으로 팀이 문제를 함께 정의하고 다음 행동을 구체화하도록 돕습니다.',en:'Help teams frame problems and act through co-design workshops, UX education and mentoring.'},scope:'Co-design · Facilitation<br>UX Education · Product Design Mentoring',filter:'learning'}
];
const projects=[
 {id:'dilly',client:'BAEMIN · DILLY',title:{ko:'발견에서 수령까지,<br>공항의 로봇 배송 경험.',en:'From discovery to pickup.<br>A robot delivery experience.'},category:['research','experience'],tags:'Field Research · Service UX',image:'dilly',type:'feature',role:{ko:'UX 전략 · 사용자 유형 및 서비스 접점 설계',en:'UX strategy · User models and service touchpoints'},summary:{ko:'공항 이용객의 이동 제약과 서비스 이용 맥락을 분석하고, 사용자 유형부터 QR 접점·픽업포인트·주문 흐름까지 연결한 프로젝트입니다.',en:'Connected airport travelers’ contexts to user models, QR touchpoints, pickup principles and ordering flows.'},details:{ko:[['상황','낯선 로봇 배송 서비스와 공항 내 이동 제약을 함께 고려해야 했습니다.'],['판단','현장 관찰에 리뷰·VoC 분석을 더해 다양한 이용 맥락을 파악했습니다.'],['설계','사용자 유형별 시나리오, 서비스 발견 접점과 수령 지점, 앱·웹 주문 흐름을 구체화했습니다.']],en:[['Context','An unfamiliar delivery service in a complex airport environment.'],['Decision','Complemented field observation with review and VoC analysis.'],['Shape','Defined user scenarios, discovery touchpoints, pickup principles and app/web flows.']]},caption:{ko:'서비스 이용 장면 · AI 재구성',en:'AI-recreated service scene'}},
 {id:'lg',client:'LG ELECTRONICS',title:{ko:'AI가 말하고 행동하는<br>경험의 기준.',en:'A shared foundation<br>for an AI agent’s behavior.'},category:['research','experience'],tags:'AI Experience · UX Framework',image:'lg',type:'feature',role:{ko:'UX Lead · 리서치 및 경험 기준 설계',en:'UX Lead · Research and experience principles'},summary:{ko:'시장·사용자·브랜드·윤리 관점을 종합해 AI Agent의 코어 페르소나, 대화 스타일과 적합성 검증 도구를 설계했습니다.',en:'Synthesized market, user, brand and ethical perspectives into core persona, dialogue guidance and a validation framework.'},details:{ko:[['상황','제품과 조직에서 함께 활용할 AI Agent 경험 기준이 필요했습니다.'],['판단','사용자·기술·브랜드·윤리를 함께 고려해 경험 방향을 정의했습니다.'],['설계','코어 페르소나와 대화 가이드, AI 윤리 기준과 적합성 검증 도구를 개발했습니다.']],en:[['Context','Product teams needed shared principles for their AI agent.'],['Decision','Considered users, technology, brand and ethics together.'],['Shape','Developed persona and dialogue guidance, ethical principles and fit-check tools.']]},caption:{ko:'포트폴리오 수록 레퍼런스 이미지',en:'Reference imagery from the portfolio'}},
 {id:'noroo',client:'NOROO PAINT',title:{ko:'대리점의 주문과<br>내부 운영을 하나로.',en:'Connecting repeat orders<br>with daily operations.'},category:['experience'],tags:'B2B Commerce · Admin UX',image:'noroo',type:'feature',role:{ko:'UX 기획 · FO/BO 화면 설계 · 구축 협업',en:'UX planning · FO/BO design · Delivery collaboration'},summary:{ko:'대리점의 반복 주문과 내부 관리 업무를 연결하는 B2B 플랫폼을 기획하고, 반응형 화면 설계부터 개발 협업·테스트·운영 가이드까지 참여했습니다.',en:'Designed a B2B platform connecting dealer ordering with internal management, from responsive screen specifications to delivery, testing and operations guidance.'},details:{ko:[['상황','대리점의 반복 주문과 내부 관리 요구를 함께 다뤄야 했습니다.'],['판단','기존 시스템과 요구사항을 바탕으로 정보 우선순위와 주문 흐름을 정리했습니다.'],['설계','FO/BO·관리자 화면과 운영 가이드를 설계하고 개발 협업·테스트를 수행했습니다.']],en:[['Context','Dealer ordering and internal administration needed to work together.'],['Decision','Reframed information priorities and flows from existing systems and requirements.'],['Shape','Designed FO/BO and admin screens and supported development, testing and operational guidance.']]},caption:{ko:'포트폴리오 수록 공개 메인 화면',en:'Public landing screen shown in the portfolio'}},
 {id:'kaist',client:'KAIST',title:{ko:'낯선 의료 공간에서도,<br>안전하게 찾는 방향.',en:'Clear direction<br>in an unfamiliar care setting.'},category:['research','experience'],tags:'Wayfinding · Spatial Experience',image:'kaist',type:'feature',role:{ko:'UX 리서치 · 시각정보체계 및 가이드라인 설계',en:'UX research · Wayfinding and design guidelines'},summary:{ko:'이동형 음압병동의 의료진·환자·운영자 동선과 과업을 분석해 공간의 정보체계, 사이니지와 적용 가이드라인을 설계했습니다.',en:'Connected staff, patient and operations journeys to a wayfinding system, signage and implementation guidelines for a mobile isolation ward.'},details:{ko:[['상황','빠르게 설치되는 임시 의료 공간에서도 명확한 길찾기와 정보 전달이 필요했습니다.'],['판단','사용자별 과업·동선·안전 위험을 함께 분석했습니다.'],['설계','구역 구분과 정보 위계, 시각체계와 현장 적용 가이드라인을 설계했습니다.']],en:[['Context','A temporary medical facility needed clear orientation and information.'],['Decision','Analyzed tasks, routes and safety risks across user groups.'],['Shape','Designed zone information, visual hierarchy and implementation guidelines.']]},caption:{ko:'포트폴리오 수록 작업',en:'Work shown in the portfolio'}},
 {id:'toolkit',client:'CO-DESIGN TOOLKIT',title:{ko:'소비자 연구를<br>함께 쓰는 기획 도구로.',en:'Consumer research.<br>A tool teams can use.'},category:['research','learning'],tags:'Research · Toolkit · Facilitation',type:'index',role:{ko:'석사학위 연구 · 툴킷 개발 · 기업 워크숍',en:'Master’s research · Toolkit development · Company workshops'},summary:{ko:'친환경 소비자 연구를 바탕으로 중소기업이 제품 기획에 활용할 코디자인 툴킷을 개발하고, 기업 대상 워크숍을 설계·운영했습니다.',en:'Translated research into sustainable consumption into a co-design toolkit and workshops to support product planning in small and medium-sized businesses.'},details:{ko:[['연구','심층 인터뷰와 행동기록을 분석해 소비자 유형과 소비 맥락을 구조화했습니다.'],['도구','연구 결과를 기업이 함께 활용할 수 있는 코디자인 툴킷으로 구체화했습니다.'],['적용','전문가 테스트와 기업 워크숍을 통해 활용 가능성을 확인했습니다.']],en:[['Research','Structured consumer contexts from interviews and behavioral diaries.'],['Toolkit','Translated findings into tools for collaborative product planning.'],['Application','Explored use through expert testing and company workshops.']]}},
 {id:'nrc',client:'국립재활원 · HCI KOREA 2020',title:{ko:'돌봄로봇 서비스를<br>함께 구체화하는 워크숍.',en:'Co-creating<br>care-robot services.'},category:['learning'],tags:'Co-creation · Care Robotics · Facilitation',type:'index',role:{ko:'코크리에이션 워크숍 퍼실리테이터 · 홍익대학교 참여 연구원',en:'Co-creation workshop facilitator · Participating researcher, Hongik University'},summary:{ko:'국립재활원 돌봄로봇 서비스 설계를 위한 코크리에이션 워크숍에 퍼실리테이터로 참여했습니다. 돌봄로봇 활용 시나리오를 바탕으로 이해관계자들이 서비스를 함께 구체화하는 과정에 참여했습니다.',en:'Participated as a facilitator in a co-creation workshop on care-robot service design with the National Rehabilitation Center, supporting stakeholders as they explored service scenarios.'},details:{ko:[['맥락','돌봄로봇의 현황과 활용 시나리오를 공유하고 서비스 설계를 논의하는 워크숍입니다.'],['주제','이승·욕창예방·배설·식사 분야의 돌봄로봇 활용 시나리오를 다뤘습니다.'],['역할','홍익대학교 참여 연구원으로 코크리에이션 워크숍 퍼실리테이션에 참여했습니다.']],en:[['Context','A workshop connecting care-robot research and use scenarios with service design.'],['Topics','Scenarios covered transfers, pressure-injury prevention, toileting and eating.'],['Role','Participated in co-creation facilitation as a researcher from Hongik University.']]}},
 {id:'education',client:'TEACHING & MENTORING',title:{ko:'생각하는 방법부터,<br>직접 만드는 경험까지.',en:'From ways of thinking<br>to making things work.'},category:['learning'],tags:'UX Education · Product Design Mentoring',type:'index',role:{ko:'백석대학교 · 프로덕트 디자인 부트캠프',en:'Baekseok University · Product Design Bootcamp'},summary:{ko:'백석대학교 UX 강의와 넥스트러너스(오즈코딩스쿨) 부트캠프에서 UX 리서치·프로덕트 디자인 교육과 프로젝트·포트폴리오 멘토링을 진행했습니다.',en:'Taught UX at Baekseok University and UX research and product design at OZ Coding School, with project and portfolio mentoring.'},details:{ko:[['대학 강의','UX 디자인 수업과 프로젝트 피드백을 진행합니다.'],['실무 교육','UX 리서치, Figma UI, AI 활용과 HTML·CSS 기초를 교육합니다.'],['멘토링','프로덕트 디자인 프로젝트와 포트폴리오의 문제 정의·설계 논리를 함께 점검합니다.']],en:[['University','UX design teaching and project feedback.'],['Bootcamp','UX research, Figma, AI-assisted work and HTML/CSS fundamentals.'],['Mentoring','Support for problem framing, design rationale and portfolio communication.']]}}
];
function renderServices(){document.querySelector('#services').innerHTML=`<div class="service-panels">${services.map((s,i)=>`<article class="service-panel ${i===0?'active':''}" data-service="${i}"><button class="service-toggle" aria-expanded="${i===0}"><span class="service-number">0${i+1}</span><h3>${s.title}</h3><span class="service-plus" aria-hidden="true">${i===0?'−':'+'}</span></button><div class="service-content"><h4>${s[lang]}</h4><p>${textOf(s.description)}</p><div class="service-scope">${s.scope}</div><button class="related-work" data-filter="${s.filter}">${lang==='ko'?'관련 작업 보기':'Explore related work'} <span aria-hidden="true">↗</span></button></div></article>`).join('')}</div>`;
document.querySelectorAll('.service-panel').forEach(panel=>{const activate=()=>{document.querySelectorAll('.service-panel').forEach(el=>{const on=el===panel;el.classList.toggle('active',on);el.querySelector('button').setAttribute('aria-expanded',on);el.querySelector('.service-plus').textContent=on?'−':'+';})};panel.addEventListener('pointerenter',e=>{if(e.pointerType==='mouse')activate()});panel.querySelector('.service-toggle').addEventListener('click',activate);panel.addEventListener('focusin',activate)});
document.querySelectorAll('.related-work').forEach(button=>button.addEventListener('click',()=>{filter=button.dataset.filter;renderWorks();document.querySelector('#works').scrollIntoView({behavior:reduce.matches?'instant':'smooth'})}));}
const workImages={dilly:'dilly.png',lg:'lg-art.png',noroo:'noroo-art.png',kaist:'kaist-portfolio.png',toolkit:'toolkit-cover.png'};
function renderWorks(){
 document.querySelector('#filters').innerHTML=categories.map(([id,ko,en])=>`<button data-category="${id}" aria-pressed="${filter===id}">${lang==='ko'?ko:en}<sup>${id==='all'?projects.length:projects.filter(p=>p.category.includes(id)).length}</sup></button>`).join('');
 const visible=projects.filter(p=>filter==='all'||p.category.includes(filter));
 const grid=document.querySelector('#projects');grid.classList.toggle('is-filtered',filter!=='all');
 grid.innerHTML=visible.map(p=>`<article class="project project-${p.id}"><button class="project-open" data-project="${p.id}" aria-label="${p.client} ${lang==='ko'?'프로젝트 보기':'View project'}"><div class="project-media media-${p.id}">${workImages[p.id]?`<img src="assets/${workImages[p.id]}" alt="${p.client}${p.caption?' · '+textOf(p.caption):''}" loading="lazy">`:`<div class="work-image-placeholder"><span>${p.client}</span><small>${lang==='ko'?'이미지 준비 중':'Image coming soon'}</small></div>`}${p.caption?`<span class="media-caption">${textOf(p.caption)}</span>`:''}<span class="project-arrow" aria-hidden="true">↗</span></div><div class="project-info"><span class="client">${p.client}</span><h3>${textOf(p.title).replaceAll('<br>',' ')}</h3><p class="project-tags">${p.tags}</p></div></button></article>`).join('');
 document.querySelector('#result-count').textContent=lang==='ko'?`${visible.length}개의 작업`:`${visible.length} works`;
 document.querySelectorAll('[data-category]').forEach(b=>b.addEventListener('click',()=>{filter=b.dataset.category;renderWorks();document.querySelector(`[data-category="${filter}"]`).focus({preventScroll:true})}));
 document.querySelectorAll('[data-project]').forEach(b=>b.addEventListener('click',()=>openProject(b.dataset.project)));
}
const dialog=document.querySelector('#project-dialog');
function openProject(id){const p=projects.find(p=>p.id===id);document.querySelector('#dialog-content').innerHTML=`<p class="client">${p.client}</p><h2 id="dialog-title">${textOf(p.title)}</h2><p class="dialog-role">${textOf(p.role)}</p><p class="dialog-summary">${textOf(p.summary)}</p>${caseImages(id)}<div class="dialog-details">${textOf(p.details).map(([label,body])=>`<div><h3>${label}</h3><p>${body}</p></div>`).join('')}</div>${caseExtra(id)}<button class="dialog-contact" data-inquiry="${p.client}">${lang==='ko'?'이런 프로젝트를 이야기하고 싶다면':'Let’s talk about a similar project'} ↗</button>`;dialog.showModal();dialog.scrollTop=0;document.body.style.overflow='hidden';}
document.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>document.body.style.overflow='');dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});
document.querySelector('#language').addEventListener('click',()=>{lang=lang==='ko'?'en':'ko';document.documentElement.lang=lang;document.querySelectorAll('[data-ko]').forEach(el=>el.innerHTML=el.dataset[lang]);const b=document.querySelector('#language');b.textContent=lang==='ko'?'EN':'KR';headerInk.querySelector('.language').textContent=b.textContent;b.setAttribute('aria-label',lang==='ko'?'Switch to English':'한국어로 전환');renderServices();renderWorks()});
renderServices();renderWorks();
